CFL condition
ECP-copa/ExaMPM pull request #43
Opened 2023-02-23 17:17 UTC by kwitaechong

add CFL condition based on wave speed c = sqrt( Bulk_modulus / rho ) and max velocity

2023-03-02 12:21 UTC, streeve requested changes

2023-03-02 12:21 UTC, streeve commented on src/ExaMPM_TimeStepControl.hpp
> +namespace TimeStepControl
Let's remove this namespace

2023-03-02 12:21 UTC, streeve commented on src/ExaMPM_TimeIntegrator.hpp
> +    double new_dt = TimeStepControl::timeStepControl( exec_space, pm, delta_t );
I think we want to be able to run with fixed or automatic timestep. Maybe only allow fixed step if it's lower than the CFL and CFL otherwise?

2023-03-08 16:56 UTC, kwitaechong commented on src/ExaMPM_TimeIntegrator.hpp
> +    double new_dt = TimeStepControl::timeStepControl( exec_space, pm, delta_t );
Agree but it is not guaranteed that the current_dt satisfies the cfl condition before cfl condition is computed because the dynamics are changed every steps. `timeStepControl` acts only if cfl condition is violated and if violated, `new_dt` will be used. I think only way we can guarantee the fixed timestep is to use sufficiently low `delta_t`

2023-03-08 19:51 UTC, streeve commented on src/ExaMPM_TimeIntegrator.hpp
> +    double new_dt = TimeStepControl::timeStepControl( exec_space, pm, delta_t );
Yeah, I see what you mean. Can you add some comments pointing out that the fixed step size will be used only if it's always below the CFL? We'll also need to update the documentation to say this is the max_dt

2023-03-09 22:07 UTC, streeve commented
@kwitaechong I updated quite a bit since the solver still assumed a fixed step size. Can you test before I approve and merge?

2023-03-09 22:08 UTC, streeve commented
@abisner can you take a quick look as well?

2023-03-10 17:40 UTC, kwitaechong commented
using `delta_t = 0.001` is already sufficiently low and thus create output file in a uniform time interval. On the other hand, using `delta_t = 0.1` violates cfl condition and the new computed `dt = 0.00134849, 0.00129002.. and so on` was used. Looks working fine

2023-03-13 15:39 UTC, streeve approved these changes

2023-04-12 20:44 UTC, merged